### ISSUE TITLE
Task canceled exception when updating

### ISSUE THREAD

**Issue by InkDragon** [AngryGuineaPig/AuroraBuilderCustomContent#4]
receiving this when attempting to download in aurora  
System.Threading.Tasks.Taskcanceledexception:
```
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Data.Files.ElementsFile.<FromUrl>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Data.Files.Updater.IndicesUpdateService.<UpdateElementsFile>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Builder.Data.Files.Updater.IndicesUpdateService.<UpdateFileEntries>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Builder.Data.Files.Updater.IndicesUpdateService.<UpdateIndexFiles>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.Presentation.ViewModels.Shell.Start.SourcesSectionViewModel.<UpdateCustomFiles>d__74.MoveNext()
```

**Comment by AngryGuineaPig** [comment]
As far as I'm aware this is just a github issue, try redownloading it later because it still works fine for me
